version: '3.4'

services:
  
  postgres_marten_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=MartenTest
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - psg-marten-data:/var/lib/postgres/data

  postgres_dashboard:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@local.me
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "7123:80"
    restart: always
    volumes: 
      - pgadmin:/root/.pgadmin

volumes:
  psg-marten-data:
  pgadmin:


